name: main-ci
on: 
  push: 
    branches: master

jobs: 
  test: 
    uses: ./.github/workflows/test.yml
  publish: 
    needs: test
    uses: ./.github/workflows/build-publish.yml
    secrets:
      npm-token: ${{ secrets.NPM_AUTH_TOKEN }} 
        
    
  
